project:
  type: book
  output-dir: ../docs

book:
  #configuraciones globales
  title: "Métodos numéricos para transferencia de calor"
  subtitle: "Notas del curso - IER UNAM 2026"
  #subtitle: "Notas del curso - IER UNAM 2026 - métodos deterministas y simulación estocástica"

  #author: "César Gael Pérez"
  #date: "25/4/2026"
  favicon: images/ier_logo.png
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  search: true
  

  #site-url: https://cleaning-data-r.ala.org.au/
  #repo-url: https://github.com/AtlasOfLivingAustralia/cleaning_data
  
  image: images/ier_logo.png
  image-alt: "A Pacific Cleaner Shrimp illustration"
  open-graph: 
    image: images/ier_logo.png
    image-alt: "A cover image with a Pacific Cleaner Shrimp illustration"
  twitter-card: 
    image: images/ier_logo.png
    image-alt: "A cover image with a Pacific Cleaner Shrimp illustration"
    card-style: summary_large_image
  sidebar:
    logo: images/UNAMmasIER_logo.png

  chapters:
    - index.qmd
    #- intro.qmd
    #- part: 001_Fenomenos_transporte/intro_FT.qmd


    - part: 002_Difusion/Intro_dif.qmd
      chapters:
        - 002_Difusion/Ley_Fourier.qmd
        - 002_Difusion/Programacion_DF.qmd
        - 002_Difusion/Difusion_por_MC.qmd
    - part: 004_Radiacion/Intro_radiacion.qmd
      chapters:
        - 004_Radiacion/Interacciones_fisicas.qmd
        - 004_Radiacion/RTE.qmd
        - 004_Radiacion/Solucion_RTE.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    mainfont: Roboto
    monofont: Fira Code
    highlight-style: arrow
    monobackgroundcolor: "#F7F7F7"
    #include-in-header: _fathom.html
   # Se necesita cuenta en fathom para rastrear
   # quien ve mi siito
    theme: 
   #   - theme.css
   #   - theme.scss #archivos de estilo
      - lumen
    #include-in-header: 
     # - text: |
      #    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">

# ==========================================
#metadata:
#  author: "César Gael Pérez Pérez"

#  description: >
#    Material de apoyo para el curso Métodos Numéricos para la
#    Transferencia de Calor. Incluye teoría, derivaciones,
#    ejemplos resueltos e implementación computacional.

#  keywords:
#    - métodos numéricos
#    - transferencia de calor
#    - diferencias finitas
#    - conducción
#    - convección
#    - radiación
#    - MATLAB
#    - Python
#    - UNAM
#    - IER

# ==========================================

execute:
  code-annotations: hover
  number-depth: 3
